from pathlib import Path

from .config import settings


TEMPLATES = [
    {
        "id": "tpl-event",
        "source_key": "event",
        "source_name": "事件数据",
        "file_name": "event-template.xlsx",
        "formats": ["csv", "xlsx"],
        "description": "用于导入事件主数据，生成 dwd_event。",
        "required_headers": [
            "事件ID",
            "事件名称",
            "事件类型",
            "品牌",
            "车型",
            "开始时间",
            "事件状态",
        ],
        "optional_headers": ["事件描述", "结束时间", "关键词"],
        "required_fields": [
            "event_id",
            "event_name",
            "event_type",
            "brand_name",
            "model_name",
            "start_time",
            "event_status",
        ],
        "optional_fields": ["event_desc", "end_time", "keyword_list"],
        "column_map": {
            "事件id": "event_id",
            "事件名称": "event_name",
            "事件类型": "event_type",
            "品牌": "brand_name",
            "车型": "model_name",
            "开始时间": "start_time",
            "结束时间": "end_time",
            "事件状态": "event_status",
            "事件描述": "event_desc",
            "关键词": "keyword_list",
        },
        "target_table": "dwd_event",
    },
    {
        "id": "tpl-content",
        "source_key": "content",
        "source_name": "内容数据",
        "file_name": "content-template.xlsx",
        "formats": ["csv", "xlsx"],
        "description": "用于导入内容明细，生成 dwd_content 与 rel_event_content。",
        "required_headers": [
            "平台",
            "原始链接",
            "作者名称",
            "标题",
            "发布时间",
        ],
        "optional_headers": [
            "内容ID",
            "事件ID",
            "作者ID",
            "作者类型",
            "是否KOL",
            "KOL领域",
            "粉丝数",
            "正文",
            "内容类型",
            "媒体形式",
            "点赞数",
            "评论数",
            "分享数",
            "收藏数",
            "播放数",
        ],
        "required_fields": [
            "platform",
            "source_url",
            "author_name",
            "title",
            "published_at",
        ],
        "optional_fields": [
            "content_id",
            "event_id",
            "author_id",
            "content_text",
            "content_type",
            "media_form",
            "like_cnt",
            "comment_cnt",
            "share_cnt",
            "favorite_cnt",
        ],
        "column_map": {
            "内容id": "content_id",
            "事件id": "event_id",
            "平台": "platform",
            "原始链接": "source_url",
            "作者id": "author_id",
            "作者名称": "author_name",
            "作者类型": "author_type",
            "是否kol": "is_kol",
            "kol领域": "kol_domain",
            "粉丝数": "fans_cnt",
            "标题": "title",
            "正文": "content_text",
            "内容类型": "content_type",
            "媒体形式": "media_form",
            "发布时间": "published_at",
            "点赞数": "like_cnt",
            "评论数": "comment_cnt",
            "分享数": "share_cnt",
            "收藏数": "favorite_cnt",
            "播放数": "view_cnt",
        },
        "target_table": "dwd_content",
    },
    {
        "id": "tpl-comment",
        "source_key": "comment",
        "source_name": "评论数据",
        "file_name": "comment-template.xlsx",
        "formats": ["csv", "xlsx", "txt"],
        "description": "用于导入评论明细，生成 dwd_comment。",
        "required_headers": [
            "所属内容ID",
            "评论作者名称",
            "评论正文",
            "发布时间",
            "观点标签",
            "意图标签",
            "情感标签",
            "用户画像",
        ],
        "optional_headers": [
            "评论ID",
            "平台",
            "评论作者ID",
            "父评论ID",
            "回复层级",
            "点赞数",
            "回复数",
            "原始链接",
            "用户阶段",
            "心智标签",
        ],
        "required_fields": [
            "content_id",
            "comment_author_name",
            "comment_text",
            "published_at",
            "opinion_tag",
            "intention_tag",
            "sentiment_tag",
            "persona_tag",
        ],
        "optional_fields": [
            "comment_id",
            "platform",
            "comment_author_id",
            "parent_comment_id",
            "reply_level",
            "like_cnt",
            "reply_cnt",
            "source_url",
            "stage_tag",
            "mindset_tag",
        ],
        "column_map": {
            "评论id": "comment_id",
            "所属内容id": "content_id",
            "平台": "platform",
            "评论作者id": "comment_author_id",
            "评论作者名称": "comment_author_name",
            "父评论id": "parent_comment_id",
            "回复层级": "reply_level",
            "评论正文": "comment_text",
            "发布时间": "published_at",
            "点赞数": "like_cnt",
            "回复数": "reply_cnt",
            "原始链接": "source_url",
            "观点标签": "opinion_tag",
            "意图标签": "intention_tag",
            "情感标签": "sentiment_tag",
            "用户画像": "persona_tag",
            "用户阶段": "stage_tag",
            "心智标签": "mindset_tag",
        },
        "target_table": "dwd_comment",
    },
    {
        "id": "tpl-account",
        "source_key": "account",
        "source_name": "账号数据",
        "file_name": "account-template.xlsx",
        "formats": ["csv", "xlsx"],
        "description": "用于导入统一账号池，生成 dwd_account。",
        "required_headers": ["平台", "账号名称"],
        "optional_headers": [
            "账号ID",
            "头像链接",
            "粉丝数",
            "关注数",
            "获赞数",
            "账号简介",
            "认证信息",
            "账号类型",
            "领域标签",
            "用户画像",
            "用户阶段",
            "画像标签",
        ],
        "required_fields": ["platform", "nickname"],
        "optional_fields": [
            "account_id",
            "avatar_url",
            "fans_cnt",
            "follow_cnt",
            "liked_cnt",
            "account_desc",
            "certification_info",
            "account_type",
            "domain_tag",
            "persona_tag",
            "stage_tag",
            "profile_tags_json",
        ],
        "column_map": {
            "平台": "platform",
            "账号id": "account_id",
            "账号名称": "nickname",
            "头像链接": "avatar_url",
            "粉丝数": "fans_cnt",
            "关注数": "follow_cnt",
            "获赞数": "liked_cnt",
            "账号简介": "account_desc",
            "认证信息": "certification_info",
            "账号类型": "account_type",
            "领域标签": "domain_tag",
            "用户画像": "persona_tag",
            "用户阶段": "stage_tag",
            "画像标签": "profile_tags_json",
        },
        "target_table": "dwd_account",
    },
    {
        "id": "tpl-journey-400",
        "source_key": "journey_400",
        "source_name": "400触点数据",
        "file_name": "journey-400-template.xlsx",
        "formats": ["csv", "xlsx"],
        "description": "用于导入400电话摘要或工单记录，生成用户旅程触点。",
        "required_headers": ["触点ID", "触点时间", "文本摘要"],
        "optional_headers": ["用户昵称", "品牌", "车型", "城市", "业务状态", "意图标签", "问题标签", "情绪标签"],
        "required_fields": ["touchpoint_id", "touchpoint_time", "touchpoint_text"],
        "optional_fields": ["user_display_name", "brand_name", "model_name", "city_name", "business_status", "intent_tag", "issue_tag", "sentiment_tag"],
        "column_map": {
            "触点id": "touchpoint_id",
            "触点时间": "touchpoint_time",
            "文本摘要": "touchpoint_text",
            "用户昵称": "user_display_name",
            "品牌": "brand_name",
            "车型": "model_name",
            "城市": "city_name",
            "业务状态": "business_status",
            "意图标签": "intent_tag",
            "问题标签": "issue_tag",
            "情绪标签": "sentiment_tag",
        },
        "target_table": "dwd_customer_touchpoint",
    },
    {
        "id": "tpl-journey-wecom",
        "source_key": "journey_wecom",
        "source_name": "企业微信触点数据",
        "file_name": "journey-wecom-template.xlsx",
        "formats": ["csv", "xlsx"],
        "description": "用于导入企业微信会话摘要或跟进记录，生成用户旅程触点。",
        "required_headers": ["触点ID", "触点时间", "文本摘要"],
        "optional_headers": ["用户昵称", "品牌", "车型", "城市", "业务状态", "意图标签", "问题标签", "情绪标签"],
        "required_fields": ["touchpoint_id", "touchpoint_time", "touchpoint_text"],
        "optional_fields": ["user_display_name", "brand_name", "model_name", "city_name", "business_status", "intent_tag", "issue_tag", "sentiment_tag"],
        "column_map": {
            "触点id": "touchpoint_id",
            "触点时间": "touchpoint_time",
            "文本摘要": "touchpoint_text",
            "用户昵称": "user_display_name",
            "品牌": "brand_name",
            "车型": "model_name",
            "城市": "city_name",
            "业务状态": "business_status",
            "意图标签": "intent_tag",
            "问题标签": "issue_tag",
            "情绪标签": "sentiment_tag",
        },
        "target_table": "dwd_customer_touchpoint",
    },
    {
        "id": "tpl-journey-dcc",
        "source_key": "journey_dcc",
        "source_name": "DCC触点数据",
        "file_name": "journey-dcc-template.xlsx",
        "formats": ["csv", "xlsx"],
        "description": "用于导入DCC线索、外呼和邀约结果，生成用户旅程触点。",
        "required_headers": ["触点ID", "触点时间", "文本摘要"],
        "optional_headers": ["用户昵称", "品牌", "车型", "城市", "业务状态", "意图标签", "问题标签", "情绪标签"],
        "required_fields": ["touchpoint_id", "touchpoint_time", "touchpoint_text"],
        "optional_fields": ["user_display_name", "brand_name", "model_name", "city_name", "business_status", "intent_tag", "issue_tag", "sentiment_tag"],
        "column_map": {
            "触点id": "touchpoint_id",
            "触点时间": "touchpoint_time",
            "文本摘要": "touchpoint_text",
            "用户昵称": "user_display_name",
            "品牌": "brand_name",
            "车型": "model_name",
            "城市": "city_name",
            "业务状态": "business_status",
            "意图标签": "intent_tag",
            "问题标签": "issue_tag",
            "情绪标签": "sentiment_tag",
        },
        "target_table": "dwd_customer_touchpoint",
    },
    {
        "id": "tpl-journey-dianping",
        "source_key": "journey_dianping",
        "source_name": "大众点评店铺触点数据",
        "file_name": "journey-dianping-template.xlsx",
        "formats": ["csv", "xlsx"],
        "description": "用于导入大众点评店铺评价，生成到店、交付和售后旅程触点。",
        "required_headers": ["触点ID", "触点时间", "文本摘要"],
        "optional_headers": ["用户昵称", "品牌", "车型", "城市", "店铺ID", "店铺名称", "评分", "业务状态", "意图标签", "问题标签", "情绪标签"],
        "required_fields": ["touchpoint_id", "touchpoint_time", "touchpoint_text"],
        "optional_fields": ["user_display_name", "brand_name", "model_name", "city_name", "store_id", "store_name", "rating_score", "business_status", "intent_tag", "issue_tag", "sentiment_tag"],
        "column_map": {
            "触点id": "touchpoint_id",
            "触点时间": "touchpoint_time",
            "文本摘要": "touchpoint_text",
            "用户昵称": "user_display_name",
            "品牌": "brand_name",
            "车型": "model_name",
            "城市": "city_name",
            "店铺id": "store_id",
            "店铺名称": "store_name",
            "评分": "rating_score",
            "业务状态": "business_status",
            "意图标签": "intent_tag",
            "问题标签": "issue_tag",
            "情绪标签": "sentiment_tag",
        },
        "target_table": "dwd_customer_touchpoint",
    },
]


def list_templates() -> list[dict]:
    base = Path(settings.template_dir)
    result = []
    for item in TEMPLATES:
        next_item = dict(item)
        next_item["download_path"] = f"/api/data-import/templates/{item['id']}/download"
        next_item["exists"] = (base / item["file_name"]).exists()
        next_item["required_fields"] = item["required_headers"]
        next_item["optional_fields"] = item["optional_headers"]
        result.append(next_item)
    return result


def get_template(template_id: str) -> dict | None:
    return next((item for item in TEMPLATES if item["id"] == template_id), None)
